// AUTO-GENERATED - DO NOT EDIT
// Generated by openapi-remote-codegen
// Source: openapi.json
//
import {
  AccessRequestClient,
  ActivityClient,
  BackfillClient,
  AlertInvitesClient,
  AlertRulesClient,
  AlertsClient,
  AlertCustomSoundsClient,
  AlexaClient,
  AnalyticsClient,
  ApsSnapshotClient,
  AuthenticationClient,
  AuthorizationClient,
  BatteryClient,
  BGCheckClient,
  BolusCalculationClient,
  BolusClient,
  CalibrationClient,
  ChartDataClient,
  ChatIdentityClient,
  ClockFacesClient,
  CompatibilityClient,
  CompressionLowClient,
  ConfigurationClient,
  ConnectorFoodEntriesClient,
  MyFitnessPalSettingsClient,
  ConnectorStatusClient,
  CorrelationClient,
  CountClient,
  DataOverviewClient,
  DebugClient,
  DeduplicationClient,
  DeviceAgeClient,
  DeviceEventClient,
  DeviceStatusClient,
  DirectGrantClient,
  DiscrepancyClient,
  EntriesClient,
  FoodClient,
  FoodsClient,
  HeartRateClient,
  InsulinCatalogClient,
  IobClient,
  LastModifiedClient,
  LoopClient,
  MealMatchingClient,
  MemberInviteClient,
  MetadataClient,
  MeterGlucoseClient,
  MigrationClient,
  MyPermissionsClient,
  MyTenantsClient,
  NoteClient,
  NotificationsClient,
  NutritionClient,
  OAuthClient,
  OidcClient,
  WellKnownClient,
  PasskeyClient,
  PatientRecordClient,
  PebbleClient,
  PredictionClient,
  ProcessingClient,
  ProfileClient,
  PumpSnapshotClient,
  RetrospectiveClient,
  RoleClient,
  SensorGlucoseClient,
  ServicesClient,
  SettingsClient,
  StateSpansClient,
  StatisticsClient,
  StatusClient,
  StepCountClient,
  SystemClient,
  SystemEventsClient,
  TenantClient,
  TimeQueryClient,
  TotpClient,
  TrackerAlertsClient,
  TrackersClient,
  TreatmentsClient,
  UISettingsClient,
  UploaderSnapshotClient,
  UserPreferencesClient,
  DDataClient,
  PropertiesClient,
  SummaryClient,
  VersionClient,
  VersionsClient,
  WebhookSettingsClient
} from "./generated/nocturne-api-client";

/**
 * API client wrapper.
 * Provides typed access to all backend endpoints.
 */
export class ApiClient {
  public readonly baseUrl: string;
  public readonly accessRequest: AccessRequestClient;
  public readonly activity: ActivityClient;
  public readonly admin: BackfillClient;
  public readonly alertInvites: AlertInvitesClient;
  public readonly alertRules: AlertRulesClient;
  public readonly alerts: AlertsClient;
  public readonly alertSounds: AlertCustomSoundsClient;
  public readonly alexa: AlexaClient;
  public readonly analytics: AnalyticsClient;
  public readonly aPSSnapshots: ApsSnapshotClient;
  public readonly authentication: AuthenticationClient;
  public readonly authorization: AuthorizationClient;
  public readonly battery: BatteryClient;
  public readonly bGChecks: BGCheckClient;
  public readonly bolusCalculations: BolusCalculationClient;
  public readonly boluses: BolusClient;
  public readonly calibrations: CalibrationClient;
  public readonly chartData: ChartDataClient;
  public readonly chatIdentity: ChatIdentityClient;
  public readonly clockFaces: ClockFacesClient;
  public readonly compatibility: CompatibilityClient;
  public readonly compressionLows: CompressionLowClient;
  public readonly configuration: ConfigurationClient;
  public readonly connectorFoodEntries: ConnectorFoodEntriesClient;
  public readonly connectorSettings: MyFitnessPalSettingsClient;
  public readonly connectorStatus: ConnectorStatusClient;
  public readonly correlation: CorrelationClient;
  public readonly count: CountClient;
  public readonly dataOverview: DataOverviewClient;
  public readonly debug: DebugClient;
  public readonly deduplication: DeduplicationClient;
  public readonly deviceAge: DeviceAgeClient;
  public readonly deviceEvents: DeviceEventClient;
  public readonly deviceStatus: DeviceStatusClient;
  public readonly directGrants: DirectGrantClient;
  public readonly discrepancy: DiscrepancyClient;
  public readonly entries: EntriesClient;
  public readonly food: FoodClient;
  public readonly foodsV4: FoodsClient;
  public readonly heartRate: HeartRateClient;
  public readonly insulins: InsulinCatalogClient;
  public readonly iob: IobClient;
  public readonly lastModified: LastModifiedClient;
  public readonly loopNotifications: LoopClient;
  public readonly mealMatching: MealMatchingClient;
  public readonly memberInvites: MemberInviteClient;
  public readonly metadata: MetadataClient;
  public readonly meterGlucose: MeterGlucoseClient;
  public readonly migration: MigrationClient;
  public readonly myPermissions: MyPermissionsClient;
  public readonly myTenants: MyTenantsClient;
  public readonly notes: NoteClient;
  public readonly notifications: NotificationsClient;
  public readonly nutrition: NutritionClient;
  public readonly oAuth: OAuthClient;
  public readonly oidc: OidcClient;
  public readonly oidcDiscovery: WellKnownClient;
  public readonly passkey: PasskeyClient;
  public readonly patientRecord: PatientRecordClient;
  public readonly pebble: PebbleClient;
  public readonly predictions: PredictionClient;
  public readonly processing: ProcessingClient;
  public readonly profile: ProfileClient;
  public readonly pumpSnapshots: PumpSnapshotClient;
  public readonly retrospective: RetrospectiveClient;
  public readonly roles: RoleClient;
  public readonly sensorGlucose: SensorGlucoseClient;
  public readonly services: ServicesClient;
  public readonly settings: SettingsClient;
  public readonly stateSpans: StateSpansClient;
  public readonly statistics: StatisticsClient;
  public readonly status: StatusClient;
  public readonly stepCount: StepCountClient;
  public readonly system: SystemClient;
  public readonly systemEvents: SystemEventsClient;
  public readonly tenant: TenantClient;
  public readonly timeQuery: TimeQueryClient;
  public readonly totp: TotpClient;
  public readonly trackerAlerts: TrackerAlertsClient;
  public readonly trackers: TrackersClient;
  public readonly treatments: TreatmentsClient;
  public readonly uiSettings: UISettingsClient;
  public readonly uploaderSnapshots: UploaderSnapshotClient;
  public readonly userPreferences: UserPreferencesClient;
  public readonly v2DData: DDataClient;
  public readonly v2Properties: PropertiesClient;
  public readonly v2Summary: SummaryClient;
  public readonly version: VersionClient;
  public readonly versions: VersionsClient;
  public readonly webhookSettings: WebhookSettingsClient;

  constructor(
    baseUrl: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
  ) {
    const apiBaseUrl = baseUrl;
    this.baseUrl = apiBaseUrl;

    this.accessRequest = new AccessRequestClient(apiBaseUrl, http);
    this.activity = new ActivityClient(apiBaseUrl, http);
    this.admin = new BackfillClient(apiBaseUrl, http);
    this.alertInvites = new AlertInvitesClient(apiBaseUrl, http);
    this.alertRules = new AlertRulesClient(apiBaseUrl, http);
    this.alerts = new AlertsClient(apiBaseUrl, http);
    this.alertSounds = new AlertCustomSoundsClient(apiBaseUrl, http);
    this.alexa = new AlexaClient(apiBaseUrl, http);
    this.analytics = new AnalyticsClient(apiBaseUrl, http);
    this.aPSSnapshots = new ApsSnapshotClient(apiBaseUrl, http);
    this.authentication = new AuthenticationClient(apiBaseUrl, http);
    this.authorization = new AuthorizationClient(apiBaseUrl, http);
    this.battery = new BatteryClient(apiBaseUrl, http);
    this.bGChecks = new BGCheckClient(apiBaseUrl, http);
    this.bolusCalculations = new BolusCalculationClient(apiBaseUrl, http);
    this.boluses = new BolusClient(apiBaseUrl, http);
    this.calibrations = new CalibrationClient(apiBaseUrl, http);
    this.chartData = new ChartDataClient(apiBaseUrl, http);
    this.chatIdentity = new ChatIdentityClient(apiBaseUrl, http);
    this.clockFaces = new ClockFacesClient(apiBaseUrl, http);
    this.compatibility = new CompatibilityClient(apiBaseUrl, http);
    this.compressionLows = new CompressionLowClient(apiBaseUrl, http);
    this.configuration = new ConfigurationClient(apiBaseUrl, http);
    this.connectorFoodEntries = new ConnectorFoodEntriesClient(apiBaseUrl, http);
    this.connectorSettings = new MyFitnessPalSettingsClient(apiBaseUrl, http);
    this.connectorStatus = new ConnectorStatusClient(apiBaseUrl, http);
    this.correlation = new CorrelationClient(apiBaseUrl, http);
    this.count = new CountClient(apiBaseUrl, http);
    this.dataOverview = new DataOverviewClient(apiBaseUrl, http);
    this.debug = new DebugClient(apiBaseUrl, http);
    this.deduplication = new DeduplicationClient(apiBaseUrl, http);
    this.deviceAge = new DeviceAgeClient(apiBaseUrl, http);
    this.deviceEvents = new DeviceEventClient(apiBaseUrl, http);
    this.deviceStatus = new DeviceStatusClient(apiBaseUrl, http);
    this.directGrants = new DirectGrantClient(apiBaseUrl, http);
    this.discrepancy = new DiscrepancyClient(apiBaseUrl, http);
    this.entries = new EntriesClient(apiBaseUrl, http);
    this.food = new FoodClient(apiBaseUrl, http);
    this.foodsV4 = new FoodsClient(apiBaseUrl, http);
    this.heartRate = new HeartRateClient(apiBaseUrl, http);
    this.insulins = new InsulinCatalogClient(apiBaseUrl, http);
    this.iob = new IobClient(apiBaseUrl, http);
    this.lastModified = new LastModifiedClient(apiBaseUrl, http);
    this.loopNotifications = new LoopClient(apiBaseUrl, http);
    this.mealMatching = new MealMatchingClient(apiBaseUrl, http);
    this.memberInvites = new MemberInviteClient(apiBaseUrl, http);
    this.metadata = new MetadataClient(apiBaseUrl, http);
    this.meterGlucose = new MeterGlucoseClient(apiBaseUrl, http);
    this.migration = new MigrationClient(apiBaseUrl, http);
    this.myPermissions = new MyPermissionsClient(apiBaseUrl, http);
    this.myTenants = new MyTenantsClient(apiBaseUrl, http);
    this.notes = new NoteClient(apiBaseUrl, http);
    this.notifications = new NotificationsClient(apiBaseUrl, http);
    this.nutrition = new NutritionClient(apiBaseUrl, http);
    this.oAuth = new OAuthClient(apiBaseUrl, http);
    this.oidc = new OidcClient(apiBaseUrl, http);
    this.oidcDiscovery = new WellKnownClient(apiBaseUrl, http);
    this.passkey = new PasskeyClient(apiBaseUrl, http);
    this.patientRecord = new PatientRecordClient(apiBaseUrl, http);
    this.pebble = new PebbleClient(apiBaseUrl, http);
    this.predictions = new PredictionClient(apiBaseUrl, http);
    this.processing = new ProcessingClient(apiBaseUrl, http);
    this.profile = new ProfileClient(apiBaseUrl, http);
    this.pumpSnapshots = new PumpSnapshotClient(apiBaseUrl, http);
    this.retrospective = new RetrospectiveClient(apiBaseUrl, http);
    this.roles = new RoleClient(apiBaseUrl, http);
    this.sensorGlucose = new SensorGlucoseClient(apiBaseUrl, http);
    this.services = new ServicesClient(apiBaseUrl, http);
    this.settings = new SettingsClient(apiBaseUrl, http);
    this.stateSpans = new StateSpansClient(apiBaseUrl, http);
    this.statistics = new StatisticsClient(apiBaseUrl, http);
    this.status = new StatusClient(apiBaseUrl, http);
    this.stepCount = new StepCountClient(apiBaseUrl, http);
    this.system = new SystemClient(apiBaseUrl, http);
    this.systemEvents = new SystemEventsClient(apiBaseUrl, http);
    this.tenant = new TenantClient(apiBaseUrl, http);
    this.timeQuery = new TimeQueryClient(apiBaseUrl, http);
    this.totp = new TotpClient(apiBaseUrl, http);
    this.trackerAlerts = new TrackerAlertsClient(apiBaseUrl, http);
    this.trackers = new TrackersClient(apiBaseUrl, http);
    this.treatments = new TreatmentsClient(apiBaseUrl, http);
    this.uiSettings = new UISettingsClient(apiBaseUrl, http);
    this.uploaderSnapshots = new UploaderSnapshotClient(apiBaseUrl, http);
    this.userPreferences = new UserPreferencesClient(apiBaseUrl, http);
    this.v2DData = new DDataClient(apiBaseUrl, http);
    this.v2Properties = new PropertiesClient(apiBaseUrl, http);
    this.v2Summary = new SummaryClient(apiBaseUrl, http);
    this.version = new VersionClient(apiBaseUrl, http);
    this.versions = new VersionsClient(apiBaseUrl, http);
    this.webhookSettings = new WebhookSettingsClient(apiBaseUrl, http);
  }
}

// Export the generated client types for use in components
export * from "./generated/nocturne-api-client";
